site_name: DockSTARTer Templates
docs_dir: docs
nav:
    - Actualbudget: apps/actualbudget.md

  - App Specifics:
    site_name: DockSTARTer Templates
docs_dir: docs
nav:
    - Actualbudget: apps/actualbudget.md
    - Adguard: apps/adguard.md
    - Adminer: apps/adminer.md
    - Airdcpp: apps/airdcpp.md
    - Airsonic: apps/airsonic.md
    - Airsonicadvanced: apps/airsonicadvanced.md
    - Amd: apps/amd.md
    - Apcupsd: apps/apcupsd.md
    - Apprise: apps/apprise.md
    - Audiobookshelf: apps/audiobookshelf.md
    - Autobrr: apps/autobrr.md
    - Azuracast: apps/azuracast.md
    - Backrest: apps/backrest.md
    - Bazarr: apps/bazarr.md
    - Beets: apps/beets.md
    - Bitwarden: apps/bitwarden.md
    - Booksonic: apps/booksonic.md
    - Booksonicair: apps/booksonicair.md
    - Bookstack: apps/bookstack.md
    - Calibre: apps/calibre.md
    - Calibreweb: apps/calibreweb.md
    - Cloudcmd: apps/cloudcmd.md
    - Cloudflareddns: apps/cloudflareddns.md
    - Codeserver: apps/codeserver.md
    - Couchpotato: apps/couchpotato.md
    - Crossseed: apps/crossseed.md
    - Dasshio: apps/dasshio.md
    - Ddclient: apps/ddclient.md
    - Deemix: apps/deemix.md
    - Deluge: apps/deluge.md
    - Delugevpn: apps/delugevpn.md
    - Doplarr: apps/doplarr.md
    - Dozzle: apps/dozzle.md
    - Duckdns: apps/duckdns.md
    - Duplicacy: apps/duplicacy.md
    - Duplicati: apps/duplicati.md
    - Emby: apps/emby.md
    - Fail2ban: apps/fail2ban.md
    - Filebot: apps/filebot.md
    - Filebrowser: apps/filebrowser.md
    - Fileflows: apps/fileflows.md
    - Fireflyiii: apps/fireflyiii.md
    - Flame: apps/flame.md
    - Flaresolverr: apps/flaresolverr.md
    - Freshrss: apps/freshrss.md
    - Gitea: apps/gitea.md
    - Glances: apps/glances.md
    - Gluetun: apps/gluetun.md
    - Goaccess: apps/goaccess.md
    - Grafana: apps/grafana.md
    - Grocy: apps/grocy.md
    - Guacamole: apps/guacamole.md
    - H5ai: apps/h5ai.md
    - Handbrake: apps/handbrake.md
    - Headphones: apps/headphones.md
    - Heimdall: apps/heimdall.md
    - Homarr: apps/homarr.md
    - Homeassistant: apps/homeassistant.md
    - Homebridge: apps/homebridge.md
    - Homepage: apps/homepage.md
    - Homer: apps/homer.md
    - Htpcmanager: apps/htpcmanager.md
    - Httpserver: apps/httpserver.md
    - Huginn: apps/huginn.md
    - Huntarr: apps/huntarr.md
    - Influxdb: apps/influxdb.md
    - Jackett: apps/jackett.md
    - Jdownloader2: apps/jdownloader2.md
    - Jellyfin: apps/jellyfin.md
    - Jellyseerr: apps/jellyseerr.md
    - Jfago: apps/jfago.md
    - Kanboard: apps/kanboard.md
    - Kavita: apps/kavita.md
    - Kitana: apps/kitana.md
    - Kiwixserve: apps/kiwixserve.md
    - Komga: apps/komga.md
    - Lazylibrarian: apps/lazylibrarian.md
    - Ldapauth: apps/ldapauth.md
    - Librespeed: apps/librespeed.md
    - Lidarr: apps/lidarr.md
    - Limnoria: apps/limnoria.md
    - Logarr: apps/logarr.md
    - Logitechmediaserver: apps/logitechmediaserver.md
    - Lyrionmusicserver: apps/lyrionmusicserver.md
    - Maintainerr: apps/maintainerr.md
    - Makemkv: apps/makemkv.md
    - Mariadb: apps/mariadb.md
    - Medusa: apps/medusa.md
    - Minecraftbedrockserver: apps/minecraftbedrockserver.md
    - Minecraftserver: apps/minecraftserver.md
    - Monitorr: apps/monitorr.md
    - Mosquitto: apps/mosquitto.md
    - Moviematch: apps/moviematch.md
    - Murmur: apps/murmur.md
    - Muximux: apps/muximux.md
    - Mylar3: apps/mylar3.md
    - Navidrome: apps/navidrome.md
    - Netdata: apps/netdata.md
    - Nextcloud: apps/nextcloud.md
    - Nginx: apps/nginx.md
    - Nodered: apps/nodered.md
    - Nzbget: apps/nzbget.md
    - Nzbgetvpn: apps/nzbgetvpn.md
    - Nzbhydra2: apps/nzbhydra2.md
    - Omadacontroller: apps/omadacontroller.md
    - Ombi: apps/ombi.md
    - Openldap: apps/openldap.md
    - Openspeedtest: apps/openspeedtest.md
    - Openvpnas: apps/openvpnas.md
    - Organizr: apps/organizr.md
    - Ouroboros: apps/ouroboros.md
    - Overseerr: apps/overseerr.md
    - Petio: apps/petio.md
    - Pgadmin: apps/pgadmin.md
    - Pgbackup: apps/pgbackup.md
    - Photoshow: apps/photoshow.md
    - Photostructure: apps/photostructure.md
    - Phpmyadmin: apps/phpmyadmin.md
    - Picard: apps/picard.md
    - Pihole: apps/pihole.md
    - Piwigo: apps/piwigo.md
    - Plex: apps/plex.md
    - Plexanisync: apps/plexanisync.md
    - Portainer: apps/portainer.md
    - Portaineragent: apps/portaineragent.md
    - Postgres: apps/postgres.md
    - Privoxyvpn: apps/privoxyvpn.md
    - Prometheus: apps/prometheus.md
    - Prowlarr: apps/prowlarr.md
    - Pyload: apps/pyload.md
    - Qbittorrent: apps/qbittorrent.md
    - Qbittorrentvpn: apps/qbittorrentvpn.md
    - Quasselcore: apps/quasselcore.md
    - Quasselweb: apps/quasselweb.md
    - Radarr: apps/radarr.md
    - Readarr: apps/readarr.md
    - Recyclarr: apps/recyclarr.md
    - Requestrr: apps/requestrr.md
    - Resiliosync: apps/resiliosync.md
    - Rsnapshot: apps/rsnapshot.md
    - Rtorrentvpn: apps/rtorrentvpn.md
    - Rustdesk: apps/rustdesk.md
    - Rutorrent: apps/rutorrent.md
    - Sabnzbd: apps/sabnzbd.md
    - Sabnzbdvpn: apps/sabnzbdvpn.md
    - Samba: apps/samba.md
    - Sickchill: apps/sickchill.md
    - Smokeping: apps/smokeping.md
    - Sonarr: apps/sonarr.md
    - Speedtest: apps/speedtest.md
    - Swag: apps/swag.md
    - Synclounge: apps/synclounge.md
    - Syncthing: apps/syncthing.md
    - Tandoor: apps/tandoor.md
    - Tautulli: apps/tautulli.md
    - Tdarr: apps/tdarr.md
    - Tdarrnode: apps/tdarrnode.md
    - Telegraf: apps/telegraf.md
    - Thelounge: apps/thelounge.md
    - Timemachine: apps/timemachine.md
    - Traefik: apps/traefik.md
    - Traktarr: apps/traktarr.md
    - Transmission: apps/transmission.md
    - Transmissionvpn: apps/transmissionvpn.md
    - Tsdproxy: apps/tsdproxy.md
    - Tvheadend: apps/tvheadend.md
    - Ubooquity: apps/ubooquity.md
    - Unificontroller: apps/unificontroller.md
    - Unmanic: apps/unmanic.md
    - Unpackerr: apps/unpackerr.md
    - Uptimekuma: apps/uptimekuma.md
    - Varken: apps/varken.md
    - Vaultwarden: apps/vaultwarden.md
    - Vsftpd: apps/vsftpd.md
    - Watchtower: apps/watchtower.md
    - Wireguard: apps/wireguard.md
    - Xbackbone: apps/xbackbone.md
    - Xteve: apps/xteve.md
    - Yacht: apps/yacht.md
    - Youtubedl: apps/youtubedl.md
    - Znc: apps/znc.md
    
