site_name: DockSTARTer Templates
docs_dir: docs/apps
nav:
    - Actualbudget: actualbudget.md
    - Adguard: adguard.md
    - Adminer: adminer.md
    - Airdcpp: airdcpp.md
    - Airsonic: airsonic.md
    - Airsonicadvanced: airsonicadvanced.md
    - Amd: amd.md
    - Apcupsd: apcupsd.md
    - Apprise: apprise.md
    - Audiobookshelf: audiobookshelf.md
    - Autobrr: autobrr.md
    - Azuracast: azuracast.md
    - Backrest: backrest.md
    - Bazarr: bazarr.md
    - Beets: beets.md
    - Bitwarden: bitwarden.md
    - Booksonic: booksonic.md
    - Booksonicair: booksonicair.md
    - Bookstack: bookstack.md
    - Calibre: calibre.md
    - Calibreweb: calibreweb.md
    - Cloudcmd: cloudcmd.md
    - Cloudflareddns: cloudflareddns.md
    - Codeserver: codeserver.md
    - Couchpotato: couchpotato.md
    - Crossseed: crossseed.md
    - Dasshio: dasshio.md
    - Ddclient: ddclient.md
    - Deemix: deemix.md
    - Deluge: deluge.md
    - Delugevpn: delugevpn.md
    - Doplarr: doplarr.md
    - Dozzle: dozzle.md
    - Duckdns: duckdns.md
    - Duplicacy: duplicacy.md
    - Duplicati: duplicati.md
    - Emby: emby.md
    - Fail2ban: fail2ban.md
    - Filebot: filebot.md
    - Filebrowser: filebrowser.md
    - Fileflows: fileflows.md
    - Fireflyiii: fireflyiii.md
    - Flame: flame.md
    - Flaresolverr: flaresolverr.md
    - Freshrss: freshrss.md
    - Gitea: gitea.md
    - Glances: glances.md
    - Gluetun: gluetun.md
    - Goaccess: goaccess.md
    - Grafana: grafana.md
    - Grocy: grocy.md
    - Guacamole: guacamole.md
    - H5ai: h5ai.md
    - Handbrake: handbrake.md
    - Headphones: headphones.md
    - Heimdall: heimdall.md
    - Homarr: homarr.md
    - Homeassistant: homeassistant.md
    - Homebridge: homebridge.md
    - Homepage: homepage.md
    - Homer: homer.md
    - Htpcmanager: htpcmanager.md
    - Httpserver: httpserver.md
    - Huginn: huginn.md
    - Huntarr: huntarr.md
    - Influxdb: influxdb.md
    - Jackett: jackett.md
    - Jdownloader2: jdownloader2.md
    - Jellyfin: jellyfin.md
    - Jellyseerr: jellyseerr.md
    - Jfago: jfago.md
    - Kanboard: kanboard.md
    - Kavita: kavita.md
    - Kitana: kitana.md
    - Kiwixserve: kiwixserve.md
    - Komga: komga.md
    - Lazylibrarian: lazylibrarian.md
    - Ldapauth: ldapauth.md
    - Librespeed: librespeed.md
    - Lidarr: lidarr.md
    - Limnoria: limnoria.md
    - Logarr: logarr.md
    - Logitechmediaserver: logitechmediaserver.md
    - Lyrionmusicserver: lyrionmusicserver.md
    - Maintainerr: maintainerr.md
    - Makemkv: makemkv.md
    - Mariadb: mariadb.md
    - Medusa: medusa.md
    - Minecraftbedrockserver: minecraftbedrockserver.md
    - Minecraftserver: minecraftserver.md
    - Monitorr: monitorr.md
    - Mosquitto: mosquitto.md
    - Moviematch: moviematch.md
    - Murmur: murmur.md
    - Muximux: muximux.md
    - Mylar3: mylar3.md
    - Navidrome: navidrome.md
    - Netdata: netdata.md
    - Nextcloud: nextcloud.md
    - Nginx: nginx.md
    - Nodered: nodered.md
    - Nzbget: nzbget.md
    - Nzbgetvpn: nzbgetvpn.md
    - Nzbhydra2: nzbhydra2.md
    - Omadacontroller: omadacontroller.md
    - Ombi: ombi.md
    - Openldap: openldap.md
    - Openspeedtest: openspeedtest.md
    - Openvpnas: openvpnas.md
    - Organizr: organizr.md
    - Ouroboros: ouroboros.md
    - Overseerr: overseerr.md
    - Petio: petio.md
    - Pgadmin: pgadmin.md
    - Pgbackup: pgbackup.md
    - Photoshow: photoshow.md
    - Photostructure: photostructure.md
    - Phpmyadmin: phpmyadmin.md
    - Picard: picard.md
    - Pihole: pihole.md
    - Piwigo: piwigo.md
    - Plex: plex.md
    - Plexanisync: plexanisync.md
    - Portainer: portainer.md
    - Portaineragent: portaineragent.md
    - Postgres: postgres.md
    - Privoxyvpn: privoxyvpn.md
    - Prometheus: prometheus.md
    - Prowlarr: prowlarr.md
    - Pyload: pyload.md
    - Qbittorrent: qbittorrent.md
    - Qbittorrentvpn: qbittorrentvpn.md
    - Quasselcore: quasselcore.md
    - Quasselweb: quasselweb.md
    - Radarr: radarr.md
    - Readarr: readarr.md
    - Recyclarr: recyclarr.md
    - Requestrr: requestrr.md
    - Resiliosync: resiliosync.md
    - Rsnapshot: rsnapshot.md
    - Rtorrentvpn: rtorrentvpn.md
    - Rustdesk: rustdesk.md
    - Rutorrent: rutorrent.md
    - Sabnzbd: sabnzbd.md
    - Sabnzbdvpn: sabnzbdvpn.md
    - Samba: samba.md
    - Sickchill: sickchill.md
    - Smokeping: smokeping.md
    - Sonarr: sonarr.md
    - Speedtest: speedtest.md
    - Swag: swag.md
    - Synclounge: synclounge.md
    - Syncthing: syncthing.md
    - Tandoor: tandoor.md
    - Tautulli: tautulli.md
    - Tdarr: tdarr.md
    - Tdarrnode: tdarrnode.md
    - Telegraf: telegraf.md
    - Thelounge: thelounge.md
    - Timemachine: timemachine.md
    - Traefik: traefik.md
    - Traktarr: traktarr.md
    - Transmission: transmission.md
    - Transmissionvpn: transmissionvpn.md
    - Tsdproxy: tsdproxy.md
    - Tvheadend: tvheadend.md
    - Ubooquity: ubooquity.md
    - Unificontroller: unificontroller.md
    - Unmanic: unmanic.md
    - Unpackerr: unpackerr.md
    - Uptimekuma: uptimekuma.md
    - Varken: varken.md
    - Vaultwarden: vaultwarden.md
    - Vsftpd: vsftpd.md
    - Watchtower: watchtower.md
    - Wireguard: wireguard.md
    - Xbackbone: xbackbone.md
    - Xteve: xteve.md
    - Yacht: yacht.md
    - Youtubedl: youtubedl.md
    - Znc: znc.md
